import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import * as core from '../dist/core.js';
const bank=JSON.parse(fs.readFileSync('dist/questions.json','utf8'));const extraBank=JSON.parse(fs.readFileSync('dist/layer2.json','utf8'));
async function boot(initial={},now=100000){const values=new Map(Object.entries(initial).map(([k,v])=>['signal432.v1.'+k,JSON.stringify(v)]));let time=now,tick;const listeners={};const root={innerHTML:'',addEventListener:(event,fn)=>listeners[event]=fn};const timer={textContent:'',classList:{toggle(){}}};const document={documentElement:{dataset:{}},querySelector:s=>s==='#app'?root:s==='#timer'?timer:null,addEventListener(){}};const localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};class Clock extends Date{static now(){return time;}}const source=fs.readFileSync('dist/app.js','utf8').replace(/^import[^\n]+\n/,'');const fn=new (Object.getPrototypeOf(async function(){}).constructor)('document','localStorage','fetch','setInterval','window','Date','crypto',...Object.keys(core),source);await fn(document,localStorage,async(url)=>({ok:true,json:async()=>url==='/layer2.json'?extraBank:bank}),cb=>tick=cb,{scrollTo(){}},Clock,crypto,...Object.entries(core).map(([k,v])=>k==='remaining'?(deadline)=>core.remaining(deadline,time):v));return {root,timer,read:k=>JSON.parse(values.get('signal432.v1.'+k)||'null'),advance:t=>{time=t;tick();},click:(action,data={})=>listeners.click({target:{closest:()=>({dataset:{action,...data}})}})};}
const saved=(deadline=110000)=>({id:'test-session',name:'Quick Practice',ids:bank.slice(0,10).map(q=>q.id),answers:{[bank[0].id]:bank[0].correct_option},marked:{},index:0,started:100000,deadline,submitted:false});
test('application auto-submits at deadline and stores a single result',async()=>{const a=await boot({session:saved()});a.click('resume');a.advance(110000);assert.match(a.root.innerHTML,/PRACTICE COMPLETE/);assert.equal(a.read('history')[0].auto,true);assert.equal(a.read('history')[0].stats.marks,1);a.advance(120000);assert.equal(a.read('history').length,1)});
test('expired session auto-submits immediately after reload',async()=>{const a=await boot({session:saved(90000)});assert.equal(a.read('session').submitted,true);assert.match(a.root.innerHTML,/Automatically submitted/)});
test('application answer, clear and review handlers persist independently',async()=>{const a=await boot({session:saved()});a.click('resume');a.click('mark');a.click('clear');assert.equal(a.read('session').answers[bank[0].id],undefined);assert.equal(a.read('session').marked[bank[0].id],true);a.click('answer',{letter:bank[0].correct_option});assert.match(a.root.innerHTML,/✓ Correct/);a.click('finish');assert.equal(a.read('history')[0].stats.marks,1)});
test('reviewing a past result does not overwrite an unfinished session',async()=>{const past={...saved(),id:'past',submitted:true,ended:99000,stats:core.score(bank.slice(0,10),{})};const a=await boot({session:saved(),history:[past]});a.click('recent',{index:'0'});a.click('review-result');a.click('next');assert.equal(a.read('session').id,'test-session');a.click('home');a.click('resume');assert.match(a.root.innerHTML,/Question 1/);assert.equal(a.read('session').submitted,false)});

test('new practice reload restores answers, current question, review and deadline',async()=>{const qs=extraBank.slice(0,100),state={...saved(200000),id:'new-session',practicePool:'new',ids:qs.map(q=>q.id),answers:{[qs[3].id]:qs[3].correct_option},marked:{[qs[3].id]:true},index:3};const a=await boot({session:state,seen:['seed-0001'],'seen.new':qs.map(q=>q.id)},110000);a.click('resume');assert.match(a.root.innerHTML,/NEW — BANK-BASED PRACTICE/);assert.match(a.root.innerHTML,/Question 4/);assert.match(a.root.innerHTML,/✓ Correct/);assert.equal(a.timer.textContent,'01:30');assert.equal(a.read('session').marked[qs[3].id],true);assert.deepEqual(a.read('seen'),['seed-0001']);});
test('mixed application result renders separate pool performance',async()=>{const qs=[bank[0],extraBank[0]],state={...saved(200000),practicePool:'mixed',ids:qs.map(q=>q.id),answers:Object.fromEntries(qs.map(q=>[q.id,q.correct_option]))};const a=await boot({session:state});a.click('resume');a.click('finish');assert.match(a.root.innerHTML,/Performance by question pool/);assert.equal(a.read('history')[0].stats.correct,2);});
